import pandas as pd
import os

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), '..', 'data', 'intermediate_results')

suggestions = {
    '¡Clonación!': 'Cloning!',
    'Arráncame la vida': 'Tear This Heart Out',
    'Dos mil uno:odisea del espacio': '2001: A Space Odyssey',
    '"asombrosa Tierra, La"': 'The Amazing Earth (Documentary)',
    'Adiós a las Vegas': 'Leaving Las Vegas',
    '"vengador del futuro, El"': 'Total Recall',
    '"tabla periódica, La"': 'The Periodic Table (Documentary)',
    '"almuerzo desnudo,El"': 'Naked Lunch',
    'Así del precipicio': 'From the Precipice',
    'Bicho de siete cabezas': 'Brainstorm',
    'Cara cortada': 'Scarface',
    '"verdad sobre el odio, La"': 'The Truth About Hate',
    'mantenidas sin sueños.Las': 'Kept and Dreamless',
    'Vivir de nuevo': 'Reprise',
    '"amores de Romaine, Los"': 'Romaine\'s Loves',
    'Luna amarga': 'Bitter Moon',
    '"imperio de la pasión, El"': 'In the Realm of Passion',
    '"mente humana, La"': 'The Human Mind (Documentary)',
    'ueve orgasmos': '9 Orgasms',
    'Por sexo o por amor': 'For Sex or For Love',
    'Retrato al natural': 'Natural Portrait',
    'La chica danesa': 'The Danish Girl',
    '"ángel borracho, El"': 'Drunken Angel',
    'Diez historias cortas de amor': '10 Short Love Stories',
    'mala educación': 'Bad Education',
    '"habitación azul, La"': 'The Blue Room',
    '"lengua de las mariposas, La"': 'Butterfly\'s Tongue',
    '"Huicholes :la mitología de un pueblo,Los Documental"': 'Huicholes: The Mythology of a People (Documentary)',
    '"Secreto en la montaña, El"': 'Brokeback Mountain',
    '"montaña de Guerrero,La"': 'The Mountain of Guerrero',
    'Mundo Maya': 'Mayan World (Documentary)',
    '"historia de Richard O, La"': 'The Story of O',
    'Jicuri Neirra :la danza del peyote': 'Jicuri Neirra: The Peyote Dance (Documentary)',
    '"manchicuepas del Tlacuache,Las"': 'The Opossum\'s Somersaults',
    'muchachos no lloran': 'Boys Don\'t Cry',
    'Batman :ataque arkaham': 'Batman: Assault on Arkham',
    'Batman el caballero de la noche regresa': 'Batman: The Dark Knight Returns',
    'Batman el misterio de la capucha roja': 'Batman: Under the Red Hood',
    '"Bleach ,3"': 'Bleach (Anime Series)',
    '"Bleach double feature, Memories of"': 'Bleach: Memories of Nobody',
    '"Bleach double feature,The diamond"': 'Bleach: The DiamondDust Rebellion',
    'Batman año uno': 'Batman: Year One',
    'El castillo de Cagliostro': 'The Castle of Cagliostro',
    'El castillo en el cielo': 'Castle in the Sky',
    'Evangelión : I. II': 'Evangelion: 1.0 You Are (Not) Alone',
    'Iron Man y Hulk': 'Iron Man & Hulk: Heroes United',
    'Kiki :entregas a domicilio': 'Kiki\'s Delivery Service',
    'Linterna verde': 'Green Lantern',
    'Mi vecino Totoro': 'My Neighbor Totoro',
    'aruto :legend of the stone': 'Naruto the Movie: Legend of the Stone of Gelel',
    'aruto shippuden :7': 'Naruto Shippuden (Anime Series)',
    'ecessary evil': 'Necessary Evil: Super-Villains of DC Comics',
    '"iños lobo , Los"': 'Wolf Children',
    '"One piece :collection, 2"': 'One Piece (Anime Series)',
    '"hijo de Batman, El"': 'Son of Batman',
    'Recuerdos del ayer': 'Only Yesterday',
    'Resident Evil :infierno': 'Resident Evil: Damnation',
    'Se levanta el viento': 'The Wind Rises',
    'Shonen jump Naruto :uncut box set 4': 'Naruto (Anime Series)',
    'La liga de la justicia :crisis en dos...': 'Justice League: Crisis on Two Earths',
    'Ahí esta el detalle': 'You\'re Missing the Point',
    'El viaje de Chihiro': 'Spirited Away',
    'Susurros del corazón': 'Whisper of the Heart',
    '"Compadre Mendoza,El(La trilogía dela..."': 'El Compadre Mendoza',
    '"imperio de la fortuna, La"': 'The Realm of Fortune',
    '"ley de Herodes , La"': 'Herod\'s Law',
    '"México, la revolución congelada"': 'Mexico: The Frozen Revolution',
    'La tumba de las luciérnagas': 'Grave of the Fireflies',
    'Animales fantásticos': 'Fantastic Beasts and Where to Find Them',
    'edad de la peseta La': 'The Age of the Peseta',
    'Intensa mente': 'Inside Out',
    '"edukadores, Los"': 'The Edukators',
    'Mil nubes de paz cercan el cielo': 'A Thousand Clouds of Peace',
    'iño Fidencio': 'The Child Fidencio',
    'Bajo la misma estrella': 'The Fault in Our Stars',
    'Ciudades de papel': 'Paper Towns',
    'LOL (Loughing out loud) [': 'LOL'
}

df = pd.DataFrame(suggestions.items(), columns=['Original Failed Title', 'Likely Corrected Title'])
df.to_csv(os.path.join(OUTPUT_DIR, 'PISO 7_cleanup_suggestions.csv'), index=False)

print("Successfully created PISO 7_cleanup_suggestions.csv")
