import pandas as pd
import os

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), '..', 'data', 'intermediate_results')

suggestions = {
    'Arthur y lo invisibles': 'Arthur and the Invisibles',
    'Atrapenlos!': 'Catch \'em!',
    '"Aristogatos, Los"': 'The Aristocats',
    '"Animalia temporada 2,3"': 'Animalia (TV Series)',
    '"Babar, el rey de los elefantes"': 'Babar: King of the Elephants',
    'Barney y su mundo de colores en sala': 'Barney: The Land of Make-Believe',
    'Barbie en el Cascanueces': 'Barbie in the Nutcracker',
    'Barney: El castillo musical de Barney en sala': 'Barney\'s Musical Castle',
    'Barney: Lee y baila conmigo en sala': 'Barney: Read with Me, Dance with Me',
    'Blanca nieves y los Siete Enanos': 'Snow White and the Seven Dwarfs',
    'Beetlejuice super fantasma': 'Beetlejuice',
    'Belleza negra': 'Black Beauty',
    'Brainy baby: Laugh & learn en sala': 'Brainy Baby: Laugh & Learn',
    'Brainy baby: Left brain en sala': 'Brainy Baby: Left Brain',
    'Brainy baby: Peek-a-boo en sala': 'Brainy Baby: Peek-a-Boo',
    '"Bionicle, renace la leyenda"': 'Bionicle: The Legend Reborn',
    'Brainy baby : Right brain en sala': 'Brainy Baby: Right Brain',
    '"Bratz, película,La"': 'Bratz: The Movie',
    'Buscando a Nemo': 'Finding Nemo',
    '"Bratz, video El"': 'Bratz: The Video',
    'Canta y Baila con Barney': 'Sing and Dance with Barney',
    '"Brujas, Las The witches"': 'The Witches',
    '"Cadáver de la novia, el"': 'Corpse Bride',
    'Cartoon craze: Daffy Duck y el dinosaurio': 'Daffy Duck and the Dinosaur',
    '"Brújula dorada, la"': 'The Golden Compass',
    'Charlie y Lola segunda temporada en sala': 'Charlie and Lola (TV Series)',
    'Charlie y la fabrica de chocolate en sala': 'Charlie and the Chocolate Factory',
    'Charlie y Lola Carlos y Lola bromeando en sala': 'Charlie and Lola (TV Series)',
    'Babe: el puerquito valiente': 'Babe',
    '"Chicas superpoderosas, las: la película"': 'The Powerpuff Girls Movie',
    'Ciento un dalmatas': '101 Dalmatians',
    '"Conde Patula, El"': 'Count Duckula',
    '"Cortos de Pixar, Los"': 'Pixar Short Films Collection',
    '"Crónicas de Narnia, las"': 'The Chronicles of Narnia',
    '"Crónicas de Spiderwick, las"': 'The Spiderwick Chronicles',
    'Cuentos que no son cuento': 'Happily N\'Ever After',
    '"Dama y el Vagabundo,La"': 'Lady and the Tramp',
    'Donde viven los monstruos': 'Where the Wild Things Are',
    'Dora salva a las sirenas': 'Dora the Explorer: Dora Saves the Mermaids',
    'Ella está encantada': 'Ella Enchanted',
    '"Era de hielo 1, La. solo en sala"': 'Ice Age',
    '"Era del hielo 2, La . solo en sala"': 'Ice Age: The Meltdown',
    'Colorin colorado este cuento se ha acabado': 'Happily N\'Ever After 2: Snow White',
    '"Cómo entrenar a tu dragón, 2 How to train your..."': 'How to Train Your Dragon 2',
    '"Era del hielo 3, La. solo en sala"': 'Ice Age: Dawn of the Dinosaurs',
    '"Esposa de Santa Claus, La"': 'The Mrs. Clause',
    '"Espantatiburones, El"': 'Shark Tale',
    '"Expreso polar, El"': 'The Polar Express',
    '"Extraño mundo de Jack, el"': 'The Nightmare Before Christmas',
    'Diviértete con Mickey': 'Fun with Mickey',
    'Dumbo/ Dumbo edición especial': 'Dumbo',
    'E.T. El extraterrestre': 'E.T. the Extra-Terrestrial',
    'Gardfield 1': 'Garfield',
    'George de la selva': 'George of the Jungle',
    '"Goofy, la película"': 'A Goofy Movie',
    '"Gran película de Piglet, la"': 'Piglet\'s Big Movie',
    'Grandes héroes': 'Big Hero 6',
    'Halo leyendas': 'Halo Legends',
    'Gardfield 2': 'Garfield: A Tail of Two Kitties',
    'Gigante de hierro': 'The Iron Giant',
    '"Guerrero coyote iguana, el"': 'The Coyote and the Iguana Warrior',
    'Hannah Montana Y Miley Cyrus en concierto: lo...': 'Hannah Montana & Miley Cyrus: Best of Both Worlds Concert',
    '"Gato, El - The cat in the hat"': 'The Cat in the Hat',
    'Hannah Montana: detrás del proyector': 'Hannah Montana: Behind the Spotlight',
    'Hans Christian Andersen: mi vida como un...': 'My Life as a Fairytale',
    'Isla del Nim': 'Nim\'s Island',
    'Jack y las habichuelas mágicas la verdadera...': 'Jack and the Beanstalk: The Real Story',
    'Jimmy Neutron: Confusión Confusa solo en sala': 'Jimmy Neutron: Confusion Fusion',
    'Jimmy Neutron: el niño genio solo en sala': 'Jimmy Neutron: Boy Genius',
    '"Goonies, Los"': 'The Goonies',
    'Jimmy Neutron: mar de problemas solo en sala': 'Jimmy Neutron: Sea of Trouble',
    'Johnny Mysto niño mágico solo en sala': 'Johnny Mysto: Boy Wizard',
    'Jorobado de nothre dame': 'The Hunchback of Notre Dame',
    '"Independencia de México para niños, La"': 'The Independence of Mexico for Children',
    'Kirikou y las bestias salvajes': 'Kirikou and the Wild Beasts',
    'Intensa mente Inside out': 'Inside Out',
    'Lo que al agua se llevó': 'Flushed Away',
    '"Libro de la selva, El- The jungle book"': 'The Jungle Book',
    '"Locuras veraniegas de Mickey, las"': 'Mickey\'s Summer Follies',
    'Lórax en busca de la trúfula perdida Dr. Seuss’': 'The Lorax',
    'Luis Pescetti/No quiero ír a dormir': 'Luis Pescetti: I Don\'t Want to Go to Sleep',
    '"Leyenda de la nahuala, la"': 'The Legend of the Nahuala',
    '"Juguetes de Navidad, Los"': 'The Christmas Toys',
    'Lilo y Stitch 2 solo en sala': 'Lilo & Stitch 2: Stitch Has a Glitch',
    'Lilo y Stich solo en sala': 'Lilo & Stitch',
    'Llegó el recreo': 'Recess: School\'s Out',
    '"Libro de Pooh, el : diviertete con mis amigos"': 'The Book of Pooh: Fun with Friends',
    'Mi pequeña biblia': 'My Little Bible',
    'Mi pobre angelito 1': 'Home Alone',
    'Mi villano favorito': 'Despicable Me',
    '"Montaña embrujada, La"': 'Race to Witch Mountain',
    'Muppets 2: Los más buscados': 'Muppets Most Wanted',
    'Max Steel vs. El oscuro enemigo': 'Max Steel: Dark Rival',
    'Megamente': 'Megamind',
    'Max Steel vs La amenaza mutante': 'Max Steel: Bio-Crisis',
    'Oliver y su pandilla': 'Oliver & Company',
    'Oz el poderoso': 'Oz the Great and Powerful',
    'Mi pobre angelito 2': 'Home Alone 2: Lost in New York',
    'Pie pequeño : La gran helada': 'The Land Before Time: The Great Freeze',
    'Pie pequeño 6 : el secreto de la roca de los...': 'The Land Before Time VI: The Secret of Saurus Rock',
    'Pie pequeño 11 : La invasión de los pequeños...': 'The Land Before Time XI: Invasion of the Tinysauruses',
    'Oye Arnold': 'Hey Arnold!',
    'Pequeñas fieras del Futbol': 'The Little Rascals',
    '"Planeta del tesoro, el"': 'Treasure Planet',
    'Pie pequeño 3 : El tiempo de la gran entrega': 'The Land Before Time III: The Time of the Great Giving',
    '"Revancha de Max, la"': 'Max\'s Revenge',
    '"Simpson, Los"': 'The Simpsons',
    'Patita de perro': 'A Dog\'s Life',
    'Pedro y el lobo': 'Peter & the Wolf',
    '"Orígen de los guardianes, el"': 'Rise of the Guardians',
    '"Princesa y el sapo, la"': 'The Princess and the Frog',
    'Pollitos en fuga': 'Chicken Run',
    'Stuart Little 3: un ratón en la familia': 'Stuart Little 3: Call of the Wild',
    'Titán A.E': 'Titan A.E.',
    'Tom y Jerry: saliendo de clases': 'Tom and Jerry: Off to School',
    '"Super clásicos infantiles/ Gigante ártico, El"': 'The Arctic Giant',
    'Una navidad con los muppets': 'The Muppet Christmas Carol',
    '"Telaraña de Charlotte, la"': 'Charlotte\'s Web',
    'Una ratoncita valiente': 'The Great Mouse Detective',
    'Vacas vaqueras': 'Home on the Range',
    '¡Vamos a cantar!': 'Let\'s Sing!',
    'Vecinos invasores': 'Over the Hedge',
    'Veinte mil leguas de viaje submarino': '20,000 Leagues Under the Sea',
    'Todos los perros van al cielo': 'All Dogs Go to Heaven',
    'Tom y Jerry y el anillo mágico': 'Tom and Jerry: The Magic Ring',
    '"Principe de Egipto, el"': 'The Prince of Egypt',
    'Wallece y Gromit: la batalla de los vegetales': 'Wallace & Gromit: The Curse of the Were-Rabbit',
    'Willy Wonka y la fàbrica de chocolate': 'Willy Wonka & the Chocolate Factory',
    'Winnie the Pooh y el pequeño efelante': 'Pooh\'s Heffalump Movie',
    '"Viento en los sauces, el : la caricatura"': 'The Wind in the Willows',
    '"Zorro y el sabueso, el"': 'The Fox and the Hound',
    '"Tostada valiente va a marte, La"': 'The Brave Little Toaster Goes to Mars'
}

df = pd.DataFrame(suggestions.items(), columns=['Original Failed Title', 'Likely Corrected Title'])
df.to_csv(os.path.join(OUTPUT_DIR, 'PELICULAS INFANTILES_cleanup_suggestions.csv'), index=False)

print("Successfully created PELICULAS INFANTILES_cleanup_suggestions.csv")
