import pandas as pd
import os

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), '..', 'data', 'intermediate_results')

suggestions = {
    'Básico y letal': 'Basic',
    'Barbarella: reina de la galaxia': 'Barbarella',
    'Con M de muerte': 'Dial M for Murder',
    'Batalla en el infierno': 'To Hell and Back',
    'Bastardos Sin Gloria': 'Inglourious Basterds',
    '"Batalla de Riddick, La"': 'The Chronicles of Riddick',
    'battle planet(La conquista del': 'Battle Planet',
    'Belle & Bella': 'Belle & Bella',
    '"Bebé de Rosemary, El 212"': 'Rosemary\'s Baby',
    'Belleza robada': 'Stealing Beauty',
    'Bernard y Doris': 'Bernard and Doris',
    'Beowulf : la leyenda': 'Beowulf',
    'Bernardita de Lourdes': 'The Song of Bernadette',
    '"Bello durmiente, El 221"': 'Sleeper',
    'Betty Fisher y otras historias': 'Betty Fisher and Other Stories',
    '"Bicicleta verde, La"': 'Wadjda',
    'Bicho de siete cabezas 231': 'Brainstorm',
    'Bienvenido paisano': 'Bienvenido paisano',
    'Blanca nieves un cuento de terror': 'Snow White: A Tale of Terror',
    'BloodRayne 2 : Deliverance': 'BloodRayne 2: Deliverance',
    'Borat : el segudo mejor reportero del...': 'Borat',
    '"Bordadoras, Las"': 'A Common Thread',
    '"Beso del juego, El"': 'The Kiss of Game',
    '"Botín de los valientes, El"': 'Kelly\'s Heroes',
    'Boxer: golpe a la vida': 'The Boxer',
    'Brigadas rojas': 'Red Brigades',
    'Buda explotó de vergüenza': 'Buddha Collapsed Out of Shame',
    '"Brujas de Eastwick, Las"': 'The Witches of Eastwick',
    'Batalla por la tierra 211': 'Battlefield Earth',
    'Búfalo Americano': 'American Buffalo',
    'Buenos días noche 261': 'Good Morning, Night',
    '"Cabaña The Schack, La 267"': 'The Shack',
    'Cacería voraz II': 'The Breed',
    'Cada loco con su tema': 'Every Man for Himself',
    'Cada quien su cine': 'To Each His Own Cinema',
    'eethoven monstruo inmortal 215': 'Immortal Beloved',
    '"Brujas de Salem, Las"': 'The Crucible',
    'Cadena de favores 276': 'Pay It Forward',
    'Caída del Halcón negro 277': 'Black Hawk Down',
    '"Cambiadora de páginas, La"': 'The Page Turner',
    '"Calle,La (la strada) 283"': 'La Strada',
    'Cambiamos pareja?': 'Change of Plans',
    'Camino del dragón. El 292': 'Way of the Dragon',
    'Callas para siempre': 'Callas Forever',
    '"Caída, La : Los últimos días de Hitler 279"': 'Downfall',
    'Camino hacia el terror 3( Abandonado': 'Wrong Turn 3: Left for Dead',
    'Campos de Esperanza 297': 'The Land of Hope',
    '"Campos de la muerte, Los"': 'The Killing Fields',
    'Cantando bajo la lluvia': 'Singin\' in the Rain',
    'Capitán América y el soldado del...': 'Captain America: The Winter Soldier',
    '"Callejón de los milagros, El"': 'Midaq Alley',
    'capitán de mar y guerra/La costa más...': 'Master and Commander: The Far Side of the World',
    'Camino hacia el terror 4 (inicio': 'Wrong Turn 4: Bloody Beginnings',
    'Canciones del segundo piso': 'Songs from the Second Floor',
    'Cara de guerra': 'Full Metal Jacket',
    'Carros de fuego': 'Chariots of Fire',
    'Carretera sangrienta 314': 'Blood Road',
    '"Casa de arena y niebla, La"': 'House of Sand and Fog',
    '"Casa de Alicia, La 319"': 'Alice\'s House',
    '"Chica terremoto, La"': 'The Girlquake',
    'Cincuenta sombras de Grey': 'Fifty Shades of Grey',
    'Cinema paradiso : la versión del...': 'Cinema Paradiso',
    '"Chofer y la señora Daisy, El"': 'Driving Miss Daisy',
    'Círculo de pasiones 377': 'Circle of Passions',
    '"Círculo de la muerte, El 376"': 'The Circle of Death',
    '"Carrera de la muerte, La"': 'Death Race',
    'La ciudad de las mujeres La cité des...': 'City of Women',
    'Ciudad de Dios City of God 381': 'City of God',
    'Ciudadano Kane': 'Citizen Kane',
    '"Ciudad del pecado, La"': 'Sin City',
    'Ciudad virtual 385': 'The Thirteenth Floor',
    '"Clan del oso cavernario, El"': 'The Clan of the Cave Bear',
    'Closer Llevados por el deseo 391': 'Closer',
    'Club de la pelea 393': 'Fight Club',
    '"Club de la buena estrella, El 392"': 'The Joy Luck Club',
    '"Ciencia del sueño, La La science des..."': 'The Science of Sleep',
    '"Cisne negro, El 379"': 'Black Swan',
    'Código de honor': 'Code of Honor',
    '"Ciudad de los niños perdidos, La 383"': 'The City of Lost Children',
    'La colina de la muerte Hamburguer...': 'Hamburger Hill',
    'Coco e Igor': 'Coco Chanel & Igor Stravinsky',
    'Código de familia': 'Family Code',
    'Códigos de guerra': 'Windtalkers',
    'Coffee y cigarettes': 'Coffee and Cigarettes',
    '"Código Da Vinci, El 401"': 'The Da Vinci Code',
    'Comando especial 21 Jump Street': '21 Jump Street',
    '"Color púrpura, El 413"': 'The Color Purple',
    '"Comer,beber, amar 419"': 'Eat Drink Man Woman',
    'Como agua para chocolate 421': 'Like Water for Chocolate',
    '"Comancheros, Los 415"': 'The Comancheros',
    'Como perder a un hombre en 10 días': 'How to Lose a Guy in 10 Days',
    'Con las alas rotas': 'With Broken Wings',
    'Conductor y el forastero. El 431': 'The Driver and the Stranger',
    'Color delcrimen.El 411': 'Freedomland',
    'Cómo matar a un ruiseñor?': 'To Kill a Mockingbird',
    'Confesiones del Sr. Schmidt About...': 'About Schmidt',
    'Corazón de caballero A Knight’s tale': 'A Knight\'s Tale',
    'Comprendiendo a Jane': 'Understanding Jane',
    'Corazón del tiempo : un viaje al...': 'Heart of Time',
    'Correo explosivo': 'Explosive Mail',
    'Corre Lola corre': 'Run Lola Run',
    'Cómo perder a tus amigos': 'How to Lose Friends & Alienate People',
    'Cosecha del diablo/ Prisión maldita': 'Devil\'s Harvest / Prison of the Dead',
    'Coronel Redl': 'Colonel Redl',
    '"Cosechador de almas,El"': 'Soul Harvester',
    'Crepúsculo - Luna Nueva': 'The Twilight Saga: New Moon',
    '"Crimen del Padre Amaro, El"': 'The Crime of Father Amaro',
    'Cuando hierve la sangre Never so few': 'Never So Few',
    'Cuando los hermanos se encuentran': 'When Brothers Meet',
    'Cuando un extraño llama': 'When a Stranger Calls',
    '"Cosecha estéril, La"': 'Barren Harvest',
    'Crimen virtual': 'Virtual Crime',
    '"Clave del éxito, La"': 'The Key to Success',
    'Cuarenta [ i. e.] 40 días': '40 Days and 40 Nights',
    'Crónicas de un zombi': 'Chronicles of a Zombie',
    '"Cuarto de los muertos, El"': 'The Room of the Dead',
    'Cuatro bodas y un funeral': 'Four Weddings and a Funeral',
    'Cuatro amantes 491': 'Four Lovers',
    '"Cuatro Fantásticos, Los"': 'Fantastic Four',
    'Cuentos de la Cabaña Desolada': 'Tales from the Bleak Cabin',
    'Cuentos de Canterbury': 'The Canterbury Tales',
    'Cuerpos ardientes': 'Body Heat',
    '"Culpa la tiene fidel, La"': 'Blame It on Fidel',
    '"Dalia Negra, La"': 'The Black Dahlia',
    'Cuatro cientos [ i. e. 400] golpes': 'The 400 Blows',
    'Cuchillo en el agua Knife in the water': 'Knife in the Water',
    '"Cuatro meses, 3 semanas y 2 dìas"': '4 Months, 3 Weeks and 2 Days',
    '"Dama de honor, La 511"': 'The Bridesmaid',
    'Daredevil : el hombre sin miedo': 'Daredevil',
    'David y Betsabé': 'David and Bathsheba',
    '"Dama y el fantasma, La 513"': 'The Ghost and Mrs. Muir',
    'De hombres y de dioses': 'Of Gods and Men',
    '"De tal padre, tal hijo Like father, like..."': 'Like Father, Like Son',
    'Decadencia del imperio americano': 'The Decline of the American Empire',
    'Damas del Mar': 'Ladies of the Sea',
    'Danza con lobos 516': 'Dances with Wolves',
    '"Decameron, El"': 'The Decameron',
    'De aquí a la eternidad': 'From Here to Eternity',
    'Demasiada Carne': 'Too Much Flesh',
    '"Demonio neón, El"': 'The Neon Demon',
    'Dentro de la piel': 'In the Skin',
    'Desafío a los gigantes Facing the...': 'Facing the Giants',
    '"Cuervo, The Crow"': 'The Crow',
    'De puerta en puerta Door to door': 'Door to Door',
    'Descubriendo el país de nunca jamás': 'Finding Neverland',
    '"Delgada línea roja, La"': 'The Thin Red Line',
    'Demonios en la puerta': 'Devils on the Doorstep',
    'Deseando amar': 'In the Mood for Love',
    'Despertar del miedo': 'Awakening of Fear',
    'Después de Lucía': 'After Lucia',
    'Destino milagroso': 'Miraculous Destiny',
    '"Día de la bestia, El"': 'The Day of the Beast',
    'Día del chacal': 'The Day of the Jackal',
    '"Día que la tierra se detuvo, El"': 'The Day the Earth Stood Still',
    '"Día que ví tu corazón, El"': 'The Day I Saw Your Heart',
    'Demetrius y los gladiadores': 'Demetrius and the Gladiators',
    '"Desierto rojo, El"': 'Red Desert',
    'Día de entrenamiento': 'Training Day',
    'Deudas de sangre 561': 'Blood Work',
    'Días de trueno': 'Days of Thunder',
    'Día de los inocentes.El': 'April Fool\'s Day',
    'Días sin huella': 'The Lost Weekend',
    '"Días del abandono, Los"': 'The Days of Abandonment',
    'Diario de una mujer poseída': 'Diary of a Possessed Woman',
    'Diarios de motocicleta': 'The Motorcycle Diaries',
    'Diez cosas que odio de ti': '10 Things I Hate About You',
    'Diez Mandamientos.Los': 'The Ten Commandments',
    'Diez mil A.C': '10,000 BC',
    'Diez. La mujer perfecta': '10',
    'Dinero fácil: la venganza': 'Easy Money II: Hard to Kill',
    '"Difícil Arte de amar,El"': 'The Difficult Art of Love',
    'Diamante de sangre': 'Blood Diamond',
    '"Diablo viste a la moda, El"': 'The Devil Wears Prada',
    '"Dioses deben estar locos, Los"': 'The Gods Must Be Crazy',
    'Diamantes para el desayuno': 'Diamonds for Breakfast',
    'Divorcio a la francesa': 'Le Divorce',
    'Django sin cadenas Django': 'Django Unchained',
    'Divorcio a la italiana': 'Divorce Italian Style',
    'Doble del diablo.El': 'The Devil\'s Double',
    'Doble riesgo': 'Double Jeopardy',
    '"Diablo dijo no, El 571"': 'The Devil Said No',
    '"Doble vida de Verónica, La La double..."': 'The Double Life of Véronique',
    'Divo : la espectacular vida de Giulio...': 'Il Divo',
    'Doce monos': '12 Monkeys',
    'Doce años esclavo': '12 Years a Slave',
    'Domicilio desconocido': 'Address Unknown',
    'Dónde estas hermano?': 'O Brother, Where Art Thou?',
    '"Dos días, una noche"': 'Two Days, One Night',
    'Dos mil uno [i.e. 2001] odisea del...': '2001: A Space Odyssey',
    'Dos mil diez (el año que hacemos...': '2010: The Year We Make Contact',
    'Desde mi cielo 551': 'The Lovely Bones',
    'Drácula la historia jamás contada': 'Dracula Untold',
    'Drácula príncipe de la tinieblas': 'Dracula: Prince of Darkness',
    'Dragón rojo 631': 'Red Dragon',
    'Drive el escape': 'Drive',
    'Dos mulas para la hermana Sara': 'Two Mules for Sister Sara',
    'Doce hombres en pugna': '12 Angry Men',
    '"Discreto encanto de la burgesía, El"': 'The Discreet Charm of the Bourgeoisie',
    'Duelo de titanes': 'Remember the Titans',
    '"Doce cero ocho, al este de Bucarest"': '12:08 East of Bucharest',
    'Dueños de la noche We own the...': 'We Own the Night',
    'Dura y peligrosa': 'Hot Pursuit',
    'Duro de matar 4.0': 'Live Free or Die Hard',
    'Duro de martar(un buen díapara...': 'A Good Day to Die Hard',
    'Ecos en la oscuridad': 'Echoes in the Darkness',
    'Ecos mortales Stir of echoes': 'Stir of Echoes',
    '"Edad de la peseta, La 651"': 'The Age of the Peseta',
    'En algún lugar de Africa Nowhere in...': 'Nowhere in Africa',
    'Emily Brontë wuthering heights 660': 'Wuthering Heights',
    'En el nombre de Dios Magdalene...': 'The Magdalene Sisters',
    'Escocés volador.El': 'The Flying Scotsman',
    'Escuadrón Gran Rojo: La...': 'The Big Red One',
    '"Escándalos del rey Jorge, Los 701"': 'The Madness of King George',
    'Escucha tu destino August Rush': 'August Rush',
    'Escuela del rock': 'School of Rock',
    'Especies III 711': 'Species III',
    'Escritores de la libertad': 'Freedom Writers',
    'Elogio del amor [videograbación]': 'In Praise of Love',
    'Espejos siniestros Mirrors 712': 'Mirrors',
    'Edipo alcalde 652': 'Oedipus Mayor',
    '"Esperanza vive en mi, La"': 'Hope Floats',
    '"Edukadores,Los 653"': 'The Edukators',
    '"Estafa maestra, La 721"': 'The Italian Job',
    'Estas ruinas que ves 723': 'These Ruins That You See',
    'Estoy viva': 'I\'m Alive',
    '"Estrangulador de Hillside, El"': 'The Hillside Strangler',
    'Espíritu de la pasión 715': 'Spirit of Passion',
    'Espionaje En Berlín 716': 'The Quiller Memorandum',
    '"Estaciones de la vida, Las"': 'Spring, Summer, Fall, Winter... and Spring',
    '"Esqueleto de la señora Morales, El 717"': 'The Skeleton of Mrs. Morales',
    'Eterno Resplandor de una mente sin...': 'Eternal Sunshine of the Spotless Mind',
    'Estrellas del sur 727': 'Southern Stars',
    'Europa zentropa Europa': 'Europa',
    '"Estafa maestra, La : faena a la italiana"': 'The Italian Job',
    'Ex Máquina no hay nada más...': 'Ex Machina',
    'Exorcista La versión nunca antes vista': 'The Exorcist',
    '"Ex mujer de mi vida, La 733"': 'The Ex-Wife of My Life',
    'Expreso de media noche': 'Midnight Express',
    'Expectro 737': 'Spectre',
    'Expreso de la muerte 741': 'Death Train',
    'Extraños en el paraíso': 'Stranger Than Paradise',
    '"Falsificadores, Los"': 'The Counterfeiters',
    'Expedientes secretos X': 'The X-Files',
    '"Expiación, deseo y pecado 739"': 'Atonement',
    '"Expreso de von Ryan, El"': 'Von Ryan\'s Express',
    'Farenheit 451 757': 'Fahrenheit 451',
    'Fauces de la noche.Las 761': 'Jaws of the Night',
    'Feast (atrapados) 763': 'Feast',
    'Estraños:Los': 'The Strangers',
    'Fidel: libertador o dictador': 'Fidel',
    '"Festin de Babette, El 767"': 'Babette\'s Feast',
    '"Fiebre del loco, La 769"': 'Fever of the Mad',
    'Festen : la celebración': 'The Celebration',
    '"Fantasma de la libertad, El 753"': 'The Phantom of Liberty',
    'Fenómeno siniestro 2': 'Grave Encounters 2',
    'La fiesta inovidable The party 772': 'The Party',
    'Final fantasy : el espíritu en nosotros 776': 'Final Fantasy: The Spirits Within',
    'Fuerzas de la naturaleza': 'Forces of Nature',
    'Fuimos héroes': 'We Were Soldiers',
    'Gattaca: experimento genético': 'Gattaca',
    '"Gendarme desconocido, El"': 'The Unknown Policeman',
    'Gente de Roma Gente di Roma': 'People of Rome',
    'Fuego Fatuo Le Feu Follet': 'The Fire Within',
    'Ghost dog: el camino del samurai': 'Ghost Dog: The Way of the Samurai',
    'Ghost. La sombra del amor': 'Ghost',
    'Gigantes de acero': 'Real Steel',
    '"Gatopardo, El 821"': 'The Leopard',
    'Golpe bajo el juego final': 'The Longest Yard',
    'Gotcha: juego de la muerte': 'Gotcha!',
    'Goya y la inquisición': 'Goya\'s Ghosts',
    '"Gran amante, El"': 'The Great Lover',
    '"Gran belleza, La"': 'The Great Beauty',
    'Gran concierto.El': 'The Concert',
    '"Gran comilona, La 851"': 'The Big Feast',
    '"Gran Dictador, El"': 'The Great Dictator',
    'Gran Gatsby': 'The Great Gatsby',
    'Gertrudis Bocanegra': 'Gertrudis Bocanegra',
    '"Gran hotel Budapest, El"': 'The Grand Budapest Hotel',
    'Gánster americano': 'American Gangster',
    '"Graduado, El"': 'The Graduate',
    '"Gran papel, El"': 'The Big Role',
    'Grandes esperanzas': 'Great Expectations',
    'Gravedad Gravity': 'Gravity',
    'Grbavica la revelación de Sara': 'Grbavica: The Land of My Dreams',
    'Greta Garbo: Ninotchka': 'Ninotchka',
'Grito de la lechuza 871': 'The Cry of the Owl',
    'Guerra de los vendedores': 'The War of the Salesmen',
    'Guerra de novias': 'Bride Wars',
    '"Guten tag, Ramón"': 'Guten Tag, Ramón',
    'Half light Belive in the beyond': 'Half Light',
    'Halloween : veinte años después': 'Halloween H20: 20 Years Later',
    'Hanna Arendt': 'Hannah Arendt',
    'Hanna y sus hermanas': 'Hannah and Her Sisters',
    'Hard Candy : niña mala': 'Hard Candy',
    'Hable con ella': 'Talk to Her',
    'Harry el sucio': 'Dirty Harry',
    '"Habitación azul, La"': 'The Blue Room',
    'Hasta el viento tiene miedo': 'Even the Wind Is Afraid',
    'Gritos y Susurros': 'Cries and Whispers',
    '"Gran Houdini, El"': 'The Great Houdini',
    'Heavy qué pesado': 'Heavy',
    'Helena de Troya : el deseo de la...': 'Helen of Troy',
    'Henry y June': 'Henry & June',
    'Hermanas diabólicas': 'Sisters of Death',
    'Herencia de familia 912': 'Family Inheritance',
    'Hermanos por siempre': 'Brothers Forever',
    'Hermosas tentaciones el diablo viste...': 'The Devil Wears Prada',
    '"Hermano sol, hermana luna 915"': 'Brother Sun, Sister Moon',
    'Heroinas The Heroic Trio': 'The Heroic Trio',
    '"Hijo de Saúl Saul fia, El"': 'Son of Saul',
    '"Hijo de la novia, El 921"': 'Son of the Bride',
    '"Halcón maltés, El"': 'The Maltese Falcon',
    'historia de Abraham:La 926': 'The Story of Abraham',
    '"Historia de Jacobo, La"': 'The Story of Jacob',
    'Historia americana X': 'American History X',
    'Historia del camello que llora': 'The Story of the Weeping Camel',
    'Historia de Sansón y Dalila :La 931': 'Samson and Delilah',
    '"Historia Oficial, La"': 'The Official Story',
    '"Historia sin fin, La"': 'The NeverEnding Story',
    'Historias cruzadas The help': 'The Help',
    'Historias de ultratumba': 'Tales from the Crypt',
    'Historias del metro': 'Subway Stories: Tales from the Underground',
    'Historias en la cocina': 'Kitchen Stories',
    'Historias mínimas': 'Intimate Stories',
    'Hitler: el nacimiento del mal': 'Hitler: The Rise of Evil',
    '"Hiroshima, mi amor"': 'Hiroshima Mon Amour',
    'Hombre de familia': 'The Family Man',
    'Hombre de marmol': 'Man of Marble',
    'Hombre en llamas Man on fire': 'Man on Fire',
    'Hombre mirando al sudeste': 'Man Facing Southeast',
    'Hombre peligroso Lord of war 951': 'Lord of War',
    'Hombres que camínan sobre la cola...': 'The Men Who Tread on the Tiger\'s Tail',
    'Hombre sin sombra 2.El': 'Hollow Man 2',
    '"Hombre sin sombra,El"': 'Hollow Man',
    'Honor de un guerrero 3.El': 'The Warrior\'s Honor 3',
    'Horda.La': 'The Horde',
    'Histeria: la historia del deseo': 'Hysteria',
    'La hora del lobo Hour of the wolf': 'Hour of the Wolf',
    'Hotel Rwanda : la matanza': 'Hotel Rwanda',
    'Hotel sin salida': 'Vacancy',
    '"Hombre sin pasado, El"': 'The Man Without a Past',
    '"Huevo de la serpiente, El"': 'The Serpent\'s Egg',
    'Hora de los héroes.La': 'The Finest Hours',
    '"Hugo, La Invención de"': 'Hugo',
    'I.A. Inteligencia artificial 977': 'A.I. Artificial Intelligence',
    'I really hate my job: realmente odio mi...': 'I Really Hate My Job',
    '"Infancia de Iván, La"': 'Ivan\'s Childhood',
    '"Infierno del odio, El"': 'High and Low',
    'Hundan al bismarck': 'Sink the Bismarck!',
    'Hulk: la muerte del hombre increíble': 'The Incredible Hulk Returns',
    'Ichi: El Asesino': 'Ichi the Killer',
    '"Informe pelícano, El"': 'The Pelican Brief',
    'Inframundo el despertar': 'Underworld: Awakening',
    'Inframundo Underworld': 'Underworld',
    '"Ingrato,El"': 'The Ungrateful',
    '"Ilusionista, El 986"': 'The Illusionist',
    '"Imperdonables unforgiven, Los 989"': 'Unforgiven',
    '"Imperio de los sentidos, El 愛のコリーダ"': 'In the Realm of the Senses',
    '"Imperio de la fortuna, El 991"': 'The Realm of Fortune',
    'Imperio del dragón.El 993': 'The Dragon Empire',
    'El imperio del sol Empire of sun': 'Empire of the Sun',
    'Hoy morirás': 'Today You Die',
    'Imaginando Argentina': 'Imagining Argentina',
    'Imágenes del más allá 987': 'Shutter',
    'Incident en una carretera perdida 997': 'Lost Highway',
    'Inocencia Robada': 'Stolen Innocence',
    'Instinto de media noche': 'Midnight Instinct',
    '"Inspector Bellamy, El"': 'Inspector Bellamy',
    'Intolerable cruelty Intolérable cruauté...': 'Intolerable Cruelty',
    'Invasores del tesoro': 'Treasure Raiders',
    '"Ilusión viaja en tranvía, La 985"': 'Illusion Travels by Streetcar',
    'Irene y yo... mi otro yo': 'Me, Myself & Irene',
    'J.C.V.D': 'JCVD',
    'Jack y Jill': 'Jack and Jill',
    'Jamás morirás': 'You Will Never Die',
    '"Ira de los dioses, La"': 'The Wrath of the Gods',
    '"Jardin del paraiso, El"': 'The Garden of Eden',
    '"Jardinero Fiel, El"': 'The Constant Gardener',
    'Jesús (la verdadera historia) 1051': 'Jesus',
    'Jinetes del espacio': 'Space Cowboys',
    '"Jinete Eléctrico, El"': 'The Electric Horseman',
    'Josie y las gatimelódicas': 'Josie and the Pussycats',
    '"Joven con el arete de perla, La"': 'Girl with a Pearl Earring',
    'Jovenes brujas': 'The Craft',
    'Jóvenes Pilotos': 'Flyboys',
    'Juana de Arco': 'The Messenger: The Story of Joan of Arc',
    'Juego de honor Coach Carter': 'Coach Carter',
    'Juego de ladrones': 'Den of Thieves',
    '"Intriga del collar, La"': 'The Affair of the Necklace',
    'Juego de lágrimas': 'The Crying Game',
    'Juego de poder': 'Power Play',
    'Iris: recuerdos imborrables': 'Iris',
    'Juegos del corazón': 'Playing by Heart',
    'Juegos diábolicos Poltergeist': 'Poltergeist',
    '"Jorobado de Notre Dame, El"': 'The Hunchback of Notre Dame',
    'Juegos mortales': 'Mortal Games',
    '"Juegos, trampas y dos armas...': 'Lock, Stock and Two Smoking Barrels',
    'Juego del miedo 2': 'Saw II',
    'Juego del miedo 5': 'Saw V',
    'Jugando a ser Dios': 'Playing God',
    'Juego sangriento': 'Bloody Game',
    '"Juego perfecto, El"': 'The Perfect Game',
    'Juego y pasión': 'Game and Passion',
    '"Joven manos de tijeras,El 1061"': 'Edward Scissorhands',
    '"juez del apocalipsis,El"': 'The Apocalypse Judge',
    '"Juno : crecer, correr y tropezar"': 'Juno',
    'Kagemusha : la sombra del guerrero': 'Kagemusha',
    'Karol el hombre que se convirtio en...': 'Karol: A Man Who Became Pope',
    'Kate y leopold': 'Kate & Leopold',
    'Kino : la leyenda del Padre Negro 1110': 'Kino',
    'Kolya : el nombre de la esperanza 1111': 'Kolya',
    'Julieta de los espíritus': 'Juliet of the Spirits',
    'Kramer contra Kramer Kramer vs...': 'Kramer vs. Kramer',
    'La la land : una historia de amor 1114': 'La La Land',
    'Ladrona de corazón 1119': 'Heart Thief',
    '"Lado profundo del mar, El 1118"': 'The Deep End of the Ocean',
    'Lágrimas del sol 1121': 'Tears of the Sun',
    'Larry Crowne (el amor llama dos...': 'Larry Crowne',
    '"Latido del tambor, El"': 'The Beat of the Drum',
    'Le Havre el puerto de la esperanza': 'Le Havre',
    '"Lengua de las mariposas, La"': 'Butterfly\'s Tongue',
    '"Ley de Herodes, La"': 'Herod\'s Law',
    '"Leyenda de las ballenas, La Whale..."': 'The Legend of the Whales',
    'Leyenda de la espada perdida.La': 'The Legend of the Lost Sword',
    'Lawrence de Arabia': 'Lawrence of Arabia',
    '"Leyenda de 1900, La"': 'The Legend of 1900',
    '"Leyenda de los invencibles, La 1141"': 'The Legend of the Invincibles',
    '"lado oscuro del corazón, El 1117"': 'The Dark Side of the Heart',
    'Leyenda del escorpión negro': 'Legend of the Black Scorpion',
    '"Leyenda de los perdidos, La"': 'Legend of the Lost',
    'Leyenda del fantasma. La': 'The Legend of the Ghost',
    'Leyendas de pasión': 'Legends of the Fall',
    'Leviathan Leviafan 1137': 'Leviathan',
    'Leyenda del indomable Cool hand...': 'Cool Hand Luke',
    'Leyenda de la velocidad. La': 'The Legend of Speed',
    '"Libros de Próspero, Los 1157"': 'Prospero\'s Books',
    '"Lenguaje del corazón, El 1135"': 'The Language of the Heart',
    '"Leyenda del jinete sin cabeza, La"': 'The Legend of Sleepy Hollow',
    '"Liga extraordinaria, La"': 'The League of Extraordinary Gentlemen',
    '"Leyendas de Rita, Las 1151"': 'The Legends of Rita',
    '"Leyes de la atracción, Las 1152"': 'Laws of Attraction',
    'Liberen a willy 2': 'Free Willy 2: The Adventure Home',
    'Lista mortal 1162': 'The Dead Pool',
    'Llanto de la mariposa': 'The Butterfly\'s Cry',
    '"Listón blanco, El"': 'The White Ribbon',
    '"Lista de Schindler, La 1163"': 'Schindler\'s List',
    'Lo que ellas quieren 1171': 'What Women Want',
    'Lobo de Wall Street 1172': 'The Wolf of Wall Street',
    'Locuras en el oeste': 'Blazing Saddles',
    'Línea mortal': 'Flatliners',
    'Limite vertical': 'Vertical Limit',
    'Luces distantes': 'Distant Lights',
    'Lujuria y traición': 'Lust, Caution',
    'Lulú en el puente 1191': 'Lulu on the Bridge',
    'Luna de Miel para Tres 1193': 'Honeymoon for Three',
    'Locos de Ira': 'Anger Management',
    '"Lunes al sol, Los"': 'Mondays in the Sun',
    'Luz silenciosa': 'Silent Light',
    'Mad Max II': 'Mad Max 2: The Road Warrior',
    '"Lugar sin límites, El"': 'The Place Without Limits',
    'Mad Max III': 'Mad Max Beyond Thunderdome',
    'Luna de papel': 'Paper Moon',
    '"Llave de Sarah, La"': 'Sarah\'s Key',
    'Luna amarga 1192': 'Bitter Moon',
    'Maestros de la noche.Los': 'Masters of the Night',
    'Luna sangrienta 1195': 'High Tension',
    '"Madre teresa, un corazón inagotable"': 'Mother Teresa',
    'Magnolias de acero': 'Steel Magnolias',
    '"Lunatico, El"': 'The Lunatic',
    '"Mago de Oz, El"': 'The Wizard of Oz',
    'Maldición de Rosewood. La': 'The Curse of Rosewood',
    'Maldición de un reflejo.La': 'The Curse of a Reflection',
    '"Mala educación, La"': 'Bad Education',
    'Manicomio siniestro': 'Sinister Asylum',
    '"Mandolina del capitán Corelli, La"': 'Captain Corelli\'s Mandolin',
    'Mansión del Pánico': 'Panic Room',
    'Mapa a las estrellas Maps to the stars': 'Maps to the Stars',
    'Marabunta': 'The Naked Jungle',
    'Malas enseñanzas': 'Bad Teacher',
    '"Marca de la bestia,La"': 'The Mark of the Beast',
    'Marcha de valientes': 'March of the Brave',
    'María llena eres de gracia': 'Maria Full of Grace',
    'Maria madre del hijo de dios': 'Mary, Mother of Jesus',
    'Más allá de la duda': 'Beyond a Reasonable Doubt',
    '"Mantenidas sin sueños, Las"': 'Kept and Dreamless',
    'Más allá de las nubes': 'Beyond the Clouds',
    'Más allá de los sueños': 'What Dreams May Come',
    'Más barato por docena': 'Cheaper by the Dozen',
    'Más grande historia jamás contada': 'The Greatest Story Ever Told',
    'Más negro que la noche': 'Darker Than Night',
    '"Marca del asesino, La"': 'The Mark of the Killer',
    'Masacre en Nueva York': 'Massacre in New York',
    'Mataría por tú Trabajo': 'I\'d Kill for Your Job',
    'Mejor que el sexo': 'Better Than Sex',
    'Media noche en parís': 'Midnight in Paris',
'Memoria de los muertos .La': 'Memory of the Dead',
    'Memoria de mis putas tristes': 'Memories of My Melancholy Whores',
    'Memorias de la señora Dalloway': 'Mrs Dalloway',
    'Memorias de una geisha': 'Memoirs of a Geisha',
    'Memorias del subdesarrollo': 'Memories of Underdevelopment',
    'Máxima riesgo': 'Maximum Risk',
    'Mente criminal. La confesión': 'Criminal Mind: The Confession',
'Mejor... imposible': 'As Good as It Gets',
    '"Mensajeros, Los"': 'The Messengers',
    'Mente indomable': 'Good Will Hunting',
    '"Marine, El"': 'The Marine',
    'Mentira verdaderas': 'True Lies',
    '"Mercader de Venecia, El"': 'The Merchant of Venice',
    'Memorias de Antonia': 'Antonia\'s Line',
    'Mi Encuentro Conmigo': 'My Encounter with Myself',
    'Mi novio atómico Blast from the past': 'Blast from the Past',
    'Mi pareja equivocada': 'My Wrong Partner',
    'Mentiras en Nueva York': 'Lies in New York',
    'Mi pareja es mi rival': 'My Partner is My Rival',
    'Metropolis Osamu Tezuka’s': 'Metropolis',
    'Mi vida como un perro': 'My Life as a Dog',
    'Mickey ojos azules': 'Mickey Blue Eyes',
    'Miedo punto com': 'FeardotCom',
    'Mi bella dama': 'My Fair Lady',
    'Mi amor inmortal': 'Immortal Beloved',
    'Mil cuatrocientos noventa y dos: la...': '1492: Conquest of Paradise',
    '"Milagro de Bern, El"': 'The Miracle of Bern',
    '"Milagro Si lo crees, todo es posible"': 'The Miracle',
    'Millenium Mambo': 'Millennium Mambo',
    '"Minas del rey Salomón, Las King..."': 'King Solomon\'s Mines',
    'Minority report Sentencia previa': 'Minority Report',
    '"Miroslava : mañana, ya no estaré aquí"': 'Miroslava',
    'Mitad Siniestra': 'The Dark Half',
    'Mis dos mujeres': 'My Two Women',
    'Mis últimos días : invasiones bárbaras': 'The Barbarian Invasions',
    'Mil novecientos ochenta y cuatro': '1984',
    'Milagros inesperados': 'The Green Mile',
    'Misión de justicia': 'Mission of Justice',
    'Miss Pettigrew un gran día para ellas :': 'Miss Pettigrew Lives for a Day',
    '"Misterio de Deauville, El"': 'The Deauville Mystery',
    'Moisés y los 10 mandamientos': 'Moses and the 10 Commandments',
    '"Momia regresa, La"': 'The Mummy Returns',
    'Monster: asesina en serie': 'Monster',
    '"Mil nubes de paz cercan el cielo, amor..."': 'A Thousand Clouds of Peace',
    'Mississippi en llamas': 'Mississippi Burning',
    'Morirse está en hebreo': 'My Mexican Shivah',
    '"Muchachos no lloran, Los"': 'Boys Don\'t Cry',
    'Muchachos perdidos': 'The Lost Boys',
    'Mucho Más que un crimen': 'Much More Than a Crime',
    'Muerte está con nosotros.La': 'Death is with Us',
    '"Muerte de un burócrata, La"': 'Death of a Bureaucrat',
    'Muerte de un Rey.La': 'To Kill a King',
    '"Muerte de un poeta, La Little ashes"': 'Little Ashes',
    '"Muerte le sienta bien, La"': 'Death Becomes Her',
    'Moscú en llamas': 'Moscow in Flames',
    '"Misterio de Salems Lot, El"': 'Salem\'s Lot',
    'Muhammad Alí: El invencible': 'Ali',
    '"Muerte y la doncella, La"': 'Death and the Maiden',
    '"Mujer de mi hermano,La"': 'The Woman of My Brother',
    'Mujeres perfectas.Las': 'The Stepford Wives',
    'Mundo cool': 'Cool World',
    '"Mundo de Sofía, El"': 'Sophie\'s World',
    'Muñeca inflable': 'Inflatable Doll',
    'Muriendo por un sueño': 'Dying for a Dream',
    '"Misterio de la libélula, El"': 'Dragonfly',
    'Música y Lágrimas': 'Music and Tears',
    'ace una Estrella': 'A Star Is Born',
    '"Mujer de arena, La"': 'Woman in the Dunes',
    'aranja mecanica': 'A Clockwork Orange',
    'aufragio': 'Shipwreck',
    'azarín': 'Nazarín',
    '"áufragos II los piratas, Los"': 'Shipwrecked II: The Pirates',
    '"Mundo está loco, loco, El"': 'It\'s a Mad, Mad, Mad, Mad World',
    'ebraska': 'Nebraska',
    'ed Kelly': 'Ned Kelly',
    'ew World [Sinsegye - Sin-se-gae]': 'New World',
    '"ew York, New York"': 'New York, New York',
    'icotina cuando el destino te da el...': 'Nicotina',
    '"Mujer que Vino del Mar, La"': 'The Woman Who Came from the Sea',
    '"iebla, La"': 'The Mist',
    'ada es para siempre': 'Nothing is Forever',
    'arciso Negro': 'Black Narcissus',
    '"ieves del Kilimanjaro, Las"': 'The Snows of Kilimanjaro',
    'inja assassin': 'Ninja Assassin',
    'ine [i.e.9] songs': '9 Songs',
    'iño del sótano. El': 'The Boy in the Basement',
    '"iño con el pijama de rayas, El"': 'The Boy in the Striped Pyjamas',
    'iños del hombre': 'Children of Men',
    'irvana': 'Nirvana',
    '"iños están Bien, Los"': 'The Kids Are All Right',
    'icholas and Alexandra': 'Nicholas and Alexandra',
    'acido para provocar el infierno': 'Born to Raise Hell',
    'quiero dormir solo': 'I Don\'t Want to Sleep Alone',
    '"ietos de don Venancio, Los"': 'The Grandsons of Don Venancio',
    '"iña de mis ojos, La"': 'The Apple of My Eye',
    '"che del crimen, La"': 'The Night of the Crime',
    '"che del Demonio, La"': 'Night of the Demon',
    'rteado': 'Raffled',
    'stalgia del pasado': 'Nostalgia for the Past',
    '"sferatu, el vampiro"': 'Nosferatu the Vampyre',
    'ticias escritas con sangre': 'News Written in Blood',
    '"via polaca, La"': 'The Polish Bride',
    'sé si cortarme las venas o...': 'I Don\'t Know Whether to Slit My Wrists or Leave Them Long',
    'temas a la oscuridad': 'Don\'t Be Afraid of the Dark',
    '"acimiento de una nación, El- The..."': 'The Birth of a Nation',
    'via que te vea': 'A Bride to Behold',
    'che del asesino': 'Night of the Killer',
    'uestra música': 'Our Music',
    '"che de los muertos vivientes, La"': 'Night of the Living Dead',
    'ueva cenicienta. La': 'A Cinderella Story',
    'ches púrpura': 'Purple Nights',
    'ueve [i.e. 9] orgasmos': '9 Orgasms',
    '"uevo mundo, El"': 'The New World',
    'unca estamos solos': 'We Are Never Alone',
    'unca Más': 'Never Again',
    'unca me abandones': 'Never Let Me Go',
    '"unca me olvides, primer amor"': 'Never Forget Me, First Love',
    'unca te dejaré': 'I Will Never Leave You',
    '"via siria, La"': 'The Syrian Bride',
    'ueva gran estafa': 'Ocean\'s Twelve',
    'viembre': 'November',
    '"via vestía de negro, La"': 'The Bride Wore Black',
    'unca te vayas sin decir te quiero Left...': 'Left Luggage',
    '"iños del brasil, Los"': 'The Boys from Brazil',
    'Ocho y media [i.e. 8 12] mujeres': '8 ½ Women',
    '"Ojos de Julia, Los"': 'Julia\'s Eyes',
    'Olvídate de París': 'Forget Paris',
    'Once a la medianoche': 'Once at Midnight',
    'Once:catorce [i.e. 11:14] : hora de morir': '11:14',
    'One hour photo ( Retratos de una...': 'One Hour Photo',
    'Operación dragón': 'Enter the Dragon',
    'Ong- Bak : el nuevo dragón': 'Ong-Bak: The Thai Warrior',
    'Obsesión Obsession': 'Obsession',
    'Operación Valkyrie': 'Valkyrie',
    'Operación Valquiria': 'Valkyrie',
    'Ojos bien cerrados': 'Eyes Wide Shut',
    'Otoño en nueva york': 'Autumn in New York',
    '"Otra cara de septiembre, La"': 'The Other Face of September',
    'Otra Huérfana.La': 'Another Orphan',
    '"Otro lado del amor, El"': 'The Other Side of Love',
    '"Otros, Los - The others"': 'The Others',
    'Pacto infernal': 'Hellbound',
    '"Paciente inglés, El"': 'The English Patient',
    'Ojos de serpiente': 'Snake Eyes',
    'Palabra y utopía': 'Word and Utopia',
    'Otra película de huevos y un pollo': 'Another Egg and Chicken Movie',
    'Pandilla salvaje The wild bunch': 'The Wild Bunch',
    'Pánico en altamar': 'Open Water',
    'Pantaleón y las visitadoras': 'Captain Pantoja and the Special Service',
    '"Otra reina, La"': 'The Other Boleyn Girl',
    '"Pantera rosa : ataca de nuevo, La"': 'The Pink Panther Strikes Again',
    'Papá por qué te fuiste': 'Dad, Why Did You Leave?',
    'Para atrapar al ladrón': 'To Catch a Thief',
    'Pare de pecar': 'Stop Sinning',
    'Padre e hijo': 'Father and Son',
    'Parecido a la felicidad': 'Something Like Happiness',
    'Pan y tulipanes': 'Bread and Tulips',
    '"Pasado me condena, El"': 'The Past Condemns Me',
    'Pandillas de Nueva York': 'Gangs of New York',
    'Pasión al atardecer': 'Evening',
    '"Panadera y el emperador, La 1511"': 'The Baker and the Emperor',
    'Pasión ilícita': 'Illicit Passion',
    'Partes usadas': 'Used Parts',
    '"París, Clara y yo"': 'Paris, Clara and I',
    '"París, te amo"': 'Paris, I Love You',
    'Pasión por áfrica': 'I Dreamed of Africa',
    'Pasiones Secretas Choses secrètes': 'Secret Things',
    'Pecados de guerra': 'Casualties of War',
    '"Peleador, El"': 'The Fighter',
    '"Pasión según Berenice, La"': 'The Passion of Berenice',
    '"Pasado nos condena, El"': 'The Past Condemns Us',
    'Pequeña miss sunshine': 'Little Miss Sunshine',
    'Pequeñas flores rojas': 'Little Red Flowers',
    'Pequeñas heridas': 'Little Wounds',
    '"Papalote azul, El"': 'The Blue Kite',
    '"Pequeño fugitivo, El"': 'Little Fugitive',
    'Pequeños milagros': 'Little Miracles',
    '"Pequeño tallarin, El"': 'The Little Noodle',
    'Perdido en Afganistán': 'Lost in Afghanistan',
    '"Pequeño Vanya, El"': 'Little Vanya',
    'Perdidos en la noche': 'Lost in the Night',
    'Perfume de mujer': 'Scent of a Woman',
    '"Perfecto asesino, El"': 'Léon: The Professional',
    '"Perfume : historia de un asesino, El"': 'Perfume: The Story of a Murderer',
    '"Perro sonriente, El"': 'The Smiling Dog',
    '"Perros de guerra, los"': 'The Dogs of War',
    'Perros de reserva': 'Reservoir Dogs',
    'Pasión de Camile Claudel Camille...': 'Camille Claudel',
    '"Pequeño Buda, El"': 'Little Buddha',
    'Pauline y Paulette': 'Pauline & Paulette',
    '"PI, el orden del caos"': 'Pi',
    'Pide al tiempo que vuelva': 'Somewhere in Time',
    'Pinceladas de fuego': 'Strokes of Fire',
    '"Piel del deseo, La"': 'The Skin of Desire',
    '"Perro Rabio, El"': 'The Rabid Dog',
    'Piso 13 .El': 'The Thirteenth Floor',
    'Plan 9 del espacio exterior': 'Plan 9 from Outer Space',
    '"Placer de la seda, El"': 'The Pleasure of Silk',
    'Pasión de los fuertes': 'My Darling Clementine',
    'Perdidos en Tokio': 'Lost in Translation',
    'Perfume de violetas': 'Violet Perfume: Nobody Hears You',
    'Pijama para dos Lover come back': 'Lover Come Back',
    'Por amor al arte The shape of things': 'The Shape of Things',
    'Por amor o por deseo': 'For Love or Desire',
    'Por el lado oscuro del camino': 'Lost Highway',
    'Posibilidad de escape': 'Possibility of Escape',
    'Planeta de los simios': 'Planet of the Apes',
    'Precio de la codicia.El': 'Margin Call',
    'Precio del mañana.El': 'In Time',
    'Precious Preciosa': 'Precious',
    'Presidente por un día': 'Dave',
    'Presagio Knowing': 'Knowing',
    'Princesa que quería vivir.La': 'The Princess Who Wanted to Live',
    '"Príncipe y yo, El - The prince and me"': 'The Prince & Me',
    'Prisionero del rock and roll': 'Jailhouse Rock',
    'Planeta de los simios. Revolución. El': 'Dawn of the Planet of the Apes',
    '"Procesos de las señoritas Vivanco, El"': 'The Trials of the Vivanco Misses',
    'Poder total': 'Absolute Power',
    '"Profecía, La - The omen"': 'The Omen',
    '"Planeta salvaje, El"': 'Fantastic Planet',
    'Pieza final.La': 'The Final Piece',
    '"Por siempre: cenicienta, una historia..."': 'Ever After: A Cinderella Story',
    'Proyecto andrómeda': 'The Andromeda Strain',
    'Profundo carmesí': 'Deep Crimson',
    'Promesa de amor': 'Promise of Love',
    '"Provocación, La : Match point"': 'Match Point',
    'Prueba de vida': 'Proof of Life',
    'PSI. I love you': 'P.S. I Love You',
    '"Próximo hombre, El"': 'The Next Man',
    'Punto de quiebra Point break': 'Point Break',
    '"Poder y La Avaricia, El"': 'Wall Street',
    'Puños de Bruce Lee': 'Bruce Lee\'s Fists of Fury',
    'Qué bello es vivir': 'It\'s a Wonderful Life',
    'Qué hacemos con Maisie?': 'What Maisie Knew',
    'Que hora es allá?': 'What Time Is It There?',
    'Quédate a mi lado': 'Stepmom',
    'Psicópata americano': 'American Psycho',
    'Quién quiere matar a Bambi?': 'Who Killed Bambi?',
    'Quieres ser John Malkovich? Being...': 'Being John Malkovich',
    '"Pueblo perdido de Switez,El"': 'The Lost Town of Switez',
    'Quiero ser famosa': 'I Want to Be Famous',
    'Quimera.La': 'Chimera',
    'Quisiera ser millonario': 'Slumdog Millionaire',
    '"Quimera de oro, La"': 'The Gold Rush',
    'Rapsodia en agosto Rhapshody in...': 'Rhapsody in August',
    '¡Que te calles!': 'Ruby & Quentin',
    'Red de mentiras': 'Body of Lies',
    'Quinto Mandamiento.El': 'The Fifth Commandment',
    '"Reglas de Víktor Vogel, Las"': 'The Rules of Viktor Vogel',
    'Regreso a Cold Mountain': 'Cold Mountain',
    'Regreso al presente': 'Blast from the Past',
    'Recien enterrados': 'Just Buried',
    '"Reina Margot, La"': 'Queen Margot',
    '"Reina de los condenados, La"': 'Queen of the Damned',
    'Reina de persia': 'One Night with the King',
    '"Red, Retirados extremadamente..."': 'RED',
    'Replicant : asesino perfecto': 'Replicant',
    'Requiem por un sueño': 'Requiem for a Dream',
    'Rescantando al soldado Ryan': 'Saving Private Ryan',
    'Retrato de una mujer casada': 'Portrait of a Married Woman',
    '"Reinado del fuego, El"': 'Reign of Fire',
    'Retratos de una pasión': 'Fur: An Imaginary Portrait of Diane Arbus',
    'Requiem por un imperio': 'Requiem for an Empire',
    'Revenant El renacido': 'The Revenant',
    '"Reventón de los nerds, El"': 'Revenge of the Nerds',
    'Rey y yo. El': 'The King and I',
    'Reyes de la calle Street kings': 'Street Kings',
    'Río místico Mystic river': 'Mystic River',
    'Río sangriento': 'Bloody River',
    'Río suzhou': 'Suzhou River',
    '"Rito de la santa muerte, El"': 'The Rite of Holy Death',
    'Revelación la señal': 'The Revelation: The Signal',
    'Rey escorpión.El': 'The Scorpion King',
    'Rey escorpión 3 .El': 'The Scorpion King 3: Battle for Redemption',
    'Reto al destino': 'An Officer and a Gentleman',
    'Rojo como el cielo': 'Red Like the Sky',
    'Roma ciudad abierta': 'Rome, Open City',
    'Romeo debe morir': 'Romeo Must Die',
    '"Saló, o, Los 120 días de Sodoma"': 'Salò, or the 120 Days of Sodom',
    '"Salvaje río, El"': 'The River Wild',
    '"Sandalias del pescador, Las - The..."': 'The Shoes of the Fisherman',
    'Sangre eterna': 'Eternal Blood',
    '"Sangre brota/ El asaltante, La"': 'The Blood Spills / The Assailant',
    '"Rey del barrio, El"': 'The King of the Neighborhood',
    'Salems Lot': 'Salem\'s Lot',
    '"Sabor de la vida, El"': 'The Taste of Life',
    'Santo contra el hacha diabólica': 'Santo vs. the Diabolical Hatchet',
    'Santo contra la mafia del vicio': 'Santo vs. the Vice Mafia',
    'Santo contra la magia negra': 'Santo vs. Black Magic',
    'Santo contra las lobas': 'Santo vs. the She-Wolves',
    'Santo en el hotel de la muerte': 'Santo in the Hotel of Death',
    'Santo en el tesoro de drácula': 'Santo in the Treasure of Dracula',
    'Santo en la frontera del terror': 'Santo on the Border of Terror',
    'Santo en la venganza de la momia': 'Santo in the Vengeance of the Mummy',
    'Santo vs el asesino de la televisión': 'Santo vs. the TV Killer',
    '"Santo Luzbel, El"': 'The Saint Luzbel',
    'Santo vs el espectro del estrangulador': 'Santo vs. the Ghost of the Strangler',
    'Santo contra la hija de Frankenstein': 'Santo vs. Frankenstein\'s Daughter',
    'Santo y Blue Demon contra el dr...': 'Santo and Blue Demon vs. the Monsters',
    'Santo contra los jinetes del terror': 'Santo vs. the Riders of Terror',
    '"Salario del miedo, El 1751"': 'The Wages of Fear',
    'Santo contra los asesinos de otros...': 'Santo vs. the Killers from Other Worlds',
    'Santo contra los hombres infernales': 'Santo vs. the Infernal Men',
    'Santo y Blue Demon en el mundo de...': 'Santo and Blue Demon in the World of the Dead',
    'Santo en el museo de cera': 'Santo in the Wax Museum',
    'Santo y Blue Demon vs Drácula y el...': 'Santo and Blue Demon vs. Dracula and the Wolf Man',
    'Santo y el águila real': 'Santo and the Royal Eagle',
    'Scar 3D': 'Scar',
    'Se busca novia The bachelor': 'The Bachelor',
    'Se busca pareja Must love dogs': 'Must Love Dogs',
    'Secreto de estado': 'State Secret',
    '"Secreto de Mary Reilly, El"': 'Mary Reilly',
    '"Secreto del Malabar princess, El"': 'The Secret of the Malabar Princess',
    'Secretos de alcoba Pillow talk': 'Pillow Talk',
    'Secretos del bosque': 'Secrets of the Forest',
    'Secretos de un matrimonio': 'Scenes from a Marriage',
    'Secretos ocultos': 'Hidden Secrets',
    'Secuestro en la familia': 'Family Abduction',
    'Secuestradores de cuerpos': 'Body Snatchers',
    'Scream3': 'Scream 3',
    'Seductor de lujo': 'Luxury Seducer',
    'Semilla de Maldad': 'Seed of Evil',
    'Sensatez Y Sentimientos': 'Sense and Sensibility',
    '"Sensualidad de Olga, La"': 'The Sensuality of Olga',
    'Señales del más allá': 'Signs from Beyond',
    '"Señor de las moscas, El"': 'Lord of the Flies',
    '"Señora Beba, La"': 'Mrs. Beba',
    'El séptimo sello [videograbación]': 'The Seventh Seal',
    '"Segundo aire, El"': 'Second Wind',
    'Sesenta segundos': 'Gone in 60 Seconds',
    'Shakespeare apasionado': 'Shakespeare in Love',
    '"Show secreto, El"': 'The Secret Show',
    'Selma: el poder de un sueño Selma': 'Selma',
    '"Siempre a tu lado, Hachiko"': 'Hachi: A Dog\'s Tale',
    '"Sexto día, El [i.e. sexto] 6° día The 6th..."': 'The 6th Day',
    'Siempre sabré lo que hiciste el verano...': 'I\'ll Always Know What You Did Last Summer',
    'Seis mujeres para un asesino': 'Blood and Black Lace',
    'Siete [ i. e. 7] días': '7 Days',
    'Siente años en el tibet': 'Seven Years in Tibet',
    '"Siete copas, El"': 'The Seven Cups',
    '"Siete Samurai, Los"': 'Seven Samurai',
    'Simón del desierto': 'Simon of the Desert',
    'Seiscientas [i.e.600] millas el tráfico de...': '600 Miles',
    'Siete [ i. e. 7] soles': '7 Suns',
    'Sr. Sra. Smith': 'Mr. & Mrs. Smith',
    'Siete almas Seven pounds': 'Seven Pounds',
    'Sr. Venganza 1861': 'Sympathy for Mr. Vengeance',
    'Sociedad de los poetas muertos': 'Dead Poets Society',
    'Solo contra sí mismo': 'Only Against Himself',
    'Sombras tenebrosas Dark shadows': 'Dark Shadows',
    'Sin edad para el amor': 'No Age for Love',
    'Sin lugar para los débiles': 'No Country for Old Men',
    'Somos Marshall We are Marshall': 'We Are Marshall',
    'Sonrisas de una noche de verano': 'Smiles of a Summer Night',
    'Soy espía': 'I Spy',
    'Soy el hermano de Josh Polonsky': 'I Am Josh Polonsky\'s Brother',
    'Soy huérfano': 'I Am an Orphan',
    'Siempre hay tiempo para reír Funny...': 'Funny People',
    'Solo los niños van al cielo 1871': 'Only Children Go to Heaven',
    'Stalker la zona': 'Stalker',
    'Su nombre es Jenifer': 'Her Name is Jenifer',
    'Sospechosos comunes': 'The Usual Suspects',
    'Starsky y Hutch 1891': 'Starsky & Hutch',
    '"Sonrisa de Monalisa, La"': 'Mona Lisa Smile',
    'Sueño de fuga': 'The Shawshank Redemption',
    'Sueños de orquesta': 'Orchestra Dreams',
    'Sueños ocultos': 'Hidden Dreams',
    'Super policias': 'Super Troopers',
    'Swordfish : Acceso autorizado': 'Swordfish',
    'Talentoso sr. ripley .El': 'The Talented Mr. Ripley',
    'Tan espeso como el chocolate': 'As Thick as Chocolate',
    'Taxi Teherán 1915': 'Taxi',
    'Temporada de sequia 1921': 'Dry Season',
    '"Tercer tiro, El"': 'The Third Shot',
    '"Tarea prohibida, La"': 'Forbidden Homework',
    'Terror a bordo': 'Terror on Board',
    '"Sueños de Akira Kurosawa, Los"': 'Dreams',
    'Terror bajo la nieve': 'Terror Under the Snow',
    'Terror en la antartida': 'Terror in Antarctica',
    'Terror en el aire': 'Terror in the Air',
    'Terror en chernóbil': 'Chernobyl Diaries',
    'Testigo mudo': 'Mute Witness',
    'The drawer boy el dibujante': 'The Drawer Boy',
    'The sweetest thing ( La cosa más...': 'The Sweetest Thing',
    'The Tenant(quimérico inquilino) El': 'The Tenant',
    'Thomas esta enamorado 1961': 'Thomas in Love',
    'Tiempo de mentir': 'Time to Lie',
    'Tiempo para morir Harsh times': 'Harsh Times',
    'La tiendita de los horrores The Little...': 'The Little Shop of Horrors',
    'Temporada de patos': 'Duck Season',
    'Tierra extranjera': 'Foreign Land',
    'Tigre y el dragón. El': 'Crouching Tiger, Hidden Dragon',
    '"Tigre y la nieve, El"': 'The Tiger and the Snow',
    'Tienes un e-mail You’ve got mail': 'You\'ve Got Mail',
    '"Tortugas pueden volar, Las"': 'Turtles Can Fly',
    '"Tierra de la gran promesa, La"': 'The Promised Land',
    'Tras la Tormenta': 'After the Storm',
    'Trenes rigurosamente vigilados': 'Closely Watched Trains',
    'Trece días': 'Thirteen Days',
    'El triángulo The Triangle': 'The Triangle',
    'Tribunal en fuga': 'Runaway Jury',
    '"Transportador, El"': 'The Transporter',
    'Tras líneas enemigas Behind enemy...': 'Behind Enemy Lines',
    'Truman show historia de una vida': 'The Truman Show',
    'Tu que estás vivo': 'You, the Living',
    'Tutia': 'Auntie',
    'Tuya en septiembre': 'Yours in September',
    '"Última noche de la humanidad, La"': 'The Last Night of Humanity',
    '"Última tentación de Cristo, La"': 'The Last Temptation of Christ',
    '"última vida en el universo, La - Ruang..."': 'Last Life in the Universe',
    '"Último emperador, El"': 'The Last Emperor',
    '"Último camino, El"': 'The Last Road',
    '"último maestro del aire, El - The last..."': 'The Last Airbender',
    '"Último paciente Chronic, El"': 'Chronic',
    '"Último rey de Escocia, El"': 'The Last King of Scotland',
    '"Último samurai, El"': 'The Last Samurai',
    '"Último tren a Auswitch, El"': 'The Last Train to Auschwitz',
    'U-Quinientos setenta y uno [i.e. 571] La...': 'U-571',
    'Un amor italiano': 'An Italian Love',
    'Un amor loco': 'A Mad Love',
    'Un amor muy especial': 'A Very Special Love',
    'Un amor surrealista Marie & Bruce': 'Marie and Bruce',
    'Un ángel enamorado': 'City of Angels',
    'Un beso más - The last kiss': 'The Last Kiss',
    'Un crimen perfecto': 'A Perfect Murder',
    'Un destello en la obscuridad': 'A Flash in the Dark',
    'Un domingo maravilloso': 'One Wonderful Sunday',
    'Tres mil [i.e.3000] millas al infierno': '3000 Miles to Graceland',
    'Un amor inesperado': 'An Unexpected Love',
    'Un dulce olor a muerte': 'A Sweet Scent of Death',
    'Un gallo con muchos huevos': 'A Rooster with Many Eggs',
    '"Últimos días de mi vida, Los"': 'The Last Days of My Life',
    'Un gato sobre el tejado caliente': 'Cat on a Hot Tin Roof',
    'Un gran chico': 'About a Boy',
    'Un hilito de sangre: un temprano...': 'A Trickle of Blood',
    'Un Hombre Solitario': 'A Single Man',
    'Un milagro para Lorenzo': 'Lorenzo\'s Oil',
    'Un monstruo de mil cabezas': 'A Monster with a Thousand Heads',
    'Un puente demasiado lejos': 'A Bridge Too Far',
    'Un regalo sangriento': 'A Bloody Gift',
    'Un sueño posible The blind side': 'The Blind Side',
    'Una acción civil': 'A Civil Action',
    'Una carta de amor': 'A Love Letter',
    'Un grito antes de morir': 'A Scream Before Dying',
    'Una chica perturbada': 'A Disturbed Girl',
    'Un horizonte lejano': 'Far and Away',
    'Una Dama sin Pudor': 'A Lady Without Shame',
    'Un milagro para Henry': 'Regarding Henry',
    'Una Eva y dos Adanes': 'Some Like It Hot',
    'Un oscuro secreto': 'A Dark Secret',
'Un Perro andaluz': 'An Andalusian Dog',
    'Una Lección de Vida': 'A Life Lesson',
    'Una muerte Inesperada': 'An Unexpected Death',
    'Una Serie de eventos Desafortunados': 'A Series of Unfortunate Events',
    'Una venus en visón': 'Venus in Fur',
    'Una vez que naces': 'Once You\'re Born You Can No Longer Hide',
    'Una vida en siete días': 'Life or Something Like It',
    'Unas dulces mentiras': 'Sweet Lies',
    'Usted es muy guapo': 'You Are So Handsome',
    'V de Venganza': 'V for Vendetta',
    'Una mirada a la oscuridad': 'A Scanner Darkly',
    'Vacaciones de invierno': 'Winter Vacation',
    'Vacaciones de Mr. Bean': 'Mr. Bean\'s Holiday',
    'Una mente Brillante': 'A Beautiful Mind',
    'Una noche en la ópera': 'A Night at the Opera',
    'Una mujer en África': 'Nowhere in Africa',
    'Una sola entrega': 'One Delivery',
    '"Valor de amar,El"': 'The Value of Loving',
    'Veinticuatro [i.e 24] en busca de la...': '24',
    'Veintiún gramos': '21 Grams',
    'Veintisiete bodas': '27 Dresses',
    'Veneno para las hadas': 'Poison for the Fairies',
    'Vacaciones en la obscuridad': 'Holidays in the Dark',
    'Vengador del futuro Total recall': 'Total Recall',
    'Vecinos y enemigos': 'Neighbors and Enemies',
    'Venganza yakuza': 'Yakuza Vengeance',
    'Ventajas de ser invisible': 'The Perks of Being a Wallflower',
    '"Ventana secreta, La"': 'Secret Window',
    '"Versión de mi vida, La"': 'Barney\'s Version',
    'Vertigo/ La sombra de una duda': 'Vertigo / Shadow of a Doubt',
    '"Versus, el combate final Versus"': 'Versus',
    'Valmont : relaciones peligrosas': 'Valmont',
    '"Viajo porque preciso, vuelvo porque te..."': 'I Travel Because I Have to, I Come Back Because I Love You',
    'Valor bajo fuego': 'Courage Under Fire',
    'Venganza despiadada': 'Merciless Vengeance',
    'Vida acuática con Steve Zissou': 'The Life Aquatic with Steve Zissou',
    '"Vida de Adele, La"': 'Blue Is the Warmest Colour',
    '"Vida de David Gale, La"': 'The Life of David Gale',
    '"Vida de los otros, La"': 'The Lives of Others',
    '"Vida es un milagro, La"': 'Life Is a Miracle',
    '"Vida prometida, La La vie promise"': 'The Promised Life',
    '"Vida conyugal, La"': 'Conjugal Life',
    'Vidas en Común': 'Lives in Common',
    'Violines en el cielo Departures': 'Departures',
    'Virgen a los 40 años': 'The 40-Year-Old Virgin',
    'Virgen y Culpable a los 41': 'Virgin and Guilty at 41',
    'Vida sin mi.La': 'My Life Without Me',
    '"Virgenes suicidas, Las"': 'The Virgin Suicides',
    '"Vida de Brian, La"': 'Life of Brian',
    'Vivir de nuevo Reprise': 'Reprise',
    'Vladimir en Buenos Aires': 'Vladimir in Buenos Aires',
    'Vodka limón': 'Vodka Lemon',
    'Volando alto Eddie the eagle': 'Eddie the Eagle',
    'Voraz Raw': 'Raw',
    '"Vuelo del fénix, El"': 'Flight of the Phoenix',
    'Vuelven los siete magníficos': 'Return of the Seven',
    'Walking on Water: cenizas en el Agua': 'Walking on Water',
    'Watchmen : relatos del navío negro': 'Watchmen: Tales of the Black Freighter',
    '"Vizconde de Montecristo, El"': 'The Viscount of Monte Cristo',
    'Y ahora damas y caballeros': 'And Now... Ladies and Gentlemen...',
    'Y dónde están las rubias? White...': 'White Chicks',
    'Viólame Baise-Moi': 'Baise-moi',
    'Ward contra ward': 'Kramer vs. Kramer',
    'Yo amo huckabees': 'I Heart Huckabees',
    'Y tú qué@v!* sabes?': 'What the Bleep Do We Know!?',
    'Whistle stop [Señal de parada]': 'Whistle Stop',
    'Zona de guerra': 'The War Zone',
    'Zona de Miedo': 'The Hurt Locker',
    'Zona Muerta.La': 'The Dead Zone',
    'Yo soy Sam': 'I Am Sam',
    '"Zapatillas rojas, Las"': 'The Red Shoes',
}

df = pd.DataFrame(suggestions.items(), columns=['Original Failed Title', 'Likely Corrected Title'])
df.to_csv(os.path.join(OUTPUT_DIR, 'CINE_cleanup_suggestions.csv'), index=False)

print("Successfully created CINE_cleanup_suggestions.csv")
